---
- hosts: localhost
  connection: local

  tasks:
    - user: name=rtorrent system=yes home=/srv/rtorrent
    - apt: name={{ item }}
      with_items:
        - rtorrent
        - tmux
    - copy: src=files/rtorrent_rc dest=~rtorrent/.rtorrent.rc owner=rtorrent group=rtorrent
    - file: path={{ item }} state=directory owner=rtorrent group=rtorrent
      with_items:
        - ~rtorrent/data
        - ~rtorrent/session
    - copy: src=files/init dest=/etc/init.d/rtorrent owner=root group=root mode=0755
    - service: name=rtorrent state=started enabled=yes
    - copy: src=files/attach_rtorrent dest=/usr/local/bin/attach_rtorrent owner=root group=root mode=0755
