#!/bin/bash

### BEGIN INIT INFO
# Provides:          rtorrent
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       rtorrent torrent client, running within tmux
### END INIT INFO

case $1 in
    start) sudo -u rtorrent tmux new-session -d -s rtorrent rtorrent ;;
    stop)  pkill -u "$(id -u rtorrent)" -f 'rtorrent$' ;;
esac
